// Code generated by hertz generator.

package llm

import (
	"github.com/Vigor-Team/youthcamp-2025-mall-be/app/gateway/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	var mws []app.HandlerFunc
	mws = append(mws, middleware.GetJwtMd().MiddlewareFunc())
	mws = append(mws, middleware.BlacklistMiddleware())
	mws = append(mws, middleware.CasbinAuth())
	return mws
}
func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _streammessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconversationidsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}
