apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:2.9.2
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/promtail/promtail.yml
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
            - name: gateway-logs
              mountPath: /logs/gateway
            - name: cart-logs
              mountPath: /logs/cart
            - name: checkout-logs
              mountPath: /logs/checkout
            - name: order-logs
              mountPath: /logs/order
            - name: payment-logs
              mountPath: /logs/payment
            - name: product-logs
              mountPath: /logs/product
            - name: user-logs
              mountPath: /logs/user
            - name: email-logs
              mountPath: /logs/email
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: gateway-logs
          hostPath:
            path: /logs/gateway
            type: Directory
        - name: cart-logs
          hostPath:
            path: /logs/cart
            type: Directory
        - name: checkout-logs
          hostPath:
            path: /logs/checkout
            type: Directory
        - name: order-logs
          hostPath:
            path: /logs/order
            type: Directory
        - name: payment-logs
          hostPath:
            path: /logs/payment
            type: Directory
        - name: product-logs
          hostPath:
            path: /logs/product
            type: Directory
        - name: user-logs
          hostPath:
            path: /logs/user
            type: Directory
        - name: email-logs
          hostPath:
            path: /logs/email
            type: Directory