apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
          imagePullPolicy: IfNotPresent
          env:
            - name: node.name
              value: "elasticsearch"
            - name: cluster.name
              value: "es-docker-cluster"
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
            - name: xpack.security.enabled # todo
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: ELASTIC_PASSWORD
              value: "123456"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          securityContext:
            privileged: true  # 解决 memlock 问题
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch